#!/bin/bash

if [ -z "$TIMEOUT" ]; then
	TIMEOUT=240
fi

if [ -z "$1" ]; then
	echo "Please provide command argument"
	exit -1
fi


if [ -z "$KMC_RNR_NOCLOBBER" ]; then
	echo "WARNING: Clobbering your guest and klee-out files. "
	echo "INFO: Big spenders set env var KMC_RNR_NOCLOBBER=1"
	rm -rf guest-*
	rm -rf klee-out-*
fi

if [ -z "$KMC_RNR_LOGREGS" ]; then
	echo "INFO: KMC_RNR_LOGREGS logs registers."
	KMC_RNR_LOGREGS=""
else
	KMC_RNR_LOGREGS="-logregs"
fi

if [ -z "$KMC_RNR_FLAGS" ]; then
	echo "INFO: KMC_RNR_FLAGS for whatever."
	KMC_RNR_FLAGS=""
fi

echo "INFO: Uses a new guest every time. Slow?"

VEXLLVM_SAVE=1 pt_run $1
ulimit -v 2200000
#-use-pcache-rewriteptr  
$CMDPREFIX klee-mc -max-memory=2048 $KMC_RNR_LOGREGS  -guest-type=sshot $KMC_RNR_FLAGS - $1 &
kmcpid="$!"
( sleep $TIMEOUT &&  kill -s SIGUSR1 $kmcpid 2>/dev/null && kill -9 $kmcpid 2>/dev/null ) &
wait $kmcpid && echo DONE

VEXLLVM_STORE_FRAGS=1 VEXLLVM_SB_LOG=stderr \
	kmc-replay 1 2>&1 | grep IMark | cut -f2 -d'(' | cut -f1 -d')' | sed "s/,//g" >con.log

mkdir sym-cov
"$VEXLLVM_HELPER_PATH"/../scripts/guest_cov.py	\
	--output-dir=sym-cov			\
	guest-last klee-last/run.istats >/dev/null

mkdir con-cov
"$VEXLLVM_HELPER_PATH"/../scripts/guest_cov.py 	\
	--output-dir=con-cov 			\
	--visited-file=con.log			\
	guest-last klee-last/run.istats >/dev/null
