#===-- runtime/Intrinsic/Makefile --------------------------*- Makefile -*--===#
#
#                     The KLEE Symbolic Virtual Machine
#
# This file is distributed under the University of Illinois Open Source
# License. See LICENSE.TXT for details.
#
#===------------------------------------------------------------------------===#

LEVEL=../..

KLEE_RUNTIME_IN=$(notdir $(wildcard *.ll))
KLEE_RUNTIME_OUT=kleej-rt.bc

include $(LEVEL)/Makefile.common
